import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:movieapp/shared/di/injection.config.dart';

final GetIt sl = GetIt.instance;

/// Initializes GetIt using code generated by `injectable`.
///
/// Run after changing DI annotations:
/// `dart run build_runner build --delete-conflicting-outputs`
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> initDependencies() async => sl.init();
